name: file_picker
description: A package that allows you to use a native file explorer to pick single or multiple absolute file paths, with extension filtering support.
homepage: https://github.com/miguelpruivo/plugins_flutter_file_picker
repository: https://github.com/miguelpruivo/flutter_file_picker
issue_tracker: https://github.com/miguelpruivo/flutter_file_picker/issues
version: 8.1.7

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_plugin_android_lifecycle:
  plugin_platform_interface:
  ffi:
  path:
  win32:
  cross_file:

dev_dependencies:
  lints: 
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.10.5"

flutter:
  plugin:
    platforms:
      android:
        package: com.mr.flutter.plugin.filepicker
        pluginClass: FilePickerPlugin
        dartPluginClass: FilePickerIO
      ios:
        pluginClass: FilePickerPlugin
        dartPluginClass: FilePickerIO
      macos:
        dartPluginClass: FilePickerMacOS
      linux:
        dartPluginClass: FilePickerLinux
